#
# Locate and configure the gRPC library
#
# Adds the following targets:
#
#  gRPC::grpc - gRPC library
#  gRPC::grpc++ - gRPC C++ library
#  gRPC::grpc++_reflection - gRPC C++ reflection library
#  gRPC::grpc_cpp_plugin - C++ generator plugin for Protocol Buffers
#

#
# Generates C++ sources from the .proto files
#
# grpc_generate_cpp (<SRCS> <HDRS> <DEST> [<ARGN>...])
#
#  SRCS - variable to define with autogenerated source files
#  HDRS - variable to define with autogenerated header files
#  DEST - directory where the source files will be created
#  ARGN - .proto files
#

# Find protobuf include directory
find_path(PROTOBUF_INCLUDE_DIR grpc/grpc.h)
mark_as_advanced(PROTOBUF_INCLUDE_DIR)

# Find libprotobuf library
find_library(PROTOBUF_LIBRARY NAMES protobuf)
mark_as_advanced(PROTOBUF_LIBRARY)
add_library(Protobuf::libprotobuf UNKNOWN IMPORTED)
set_target_properties(Protobuf::libprotobuf PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${PROTOBUF_INCLUDE_DIR}
    INTERFACE_LINK_LIBRARIES "-lpthread;-ldl"
    IMPORTED_LOCATION ${PROTOBUF_LIBRARY}
)

# Find libprotoc library
find_library(PROTOC_LIBRARY NAMES protoc)
mark_as_advanced(PROTOC_LIBRARY)
add_library(Protobuf::libprotoc UNKNOWN IMPORTED)
set_target_properties(Protobuf::libprotoc PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${PROTOBUF_INCLUDE_DIR}
    INTERFACE_LINK_LIBRARIES "-lpthread;-ldl"
    IMPORTED_LOCATION ${PROTOC_LIBRARY}
)

# Find Protobuf compiler
find_program(PROTOBUF_COMPILER NAMES protoc)
mark_as_advanced(PROTOBUF_COMPILER)
add_executable(Protobuf::protoc IMPORTED)
set_target_properties(Protobuf::protoc PROPERTIES
    IMPORTED_LOCATION ${PROTOBUF_COMPILER}
)

include(${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Protobuf DEFAULT_MSG PROTOBUF_LIBRARY)
